export const defaultPermissions = {
  super_admin: {
    product: { add: false, delete: true, edit: true, view: true },
    category: { add: true, delete: true, edit: true, view: true },
    company: { add: true, delete: true, edit: true, view: true },
    unit: { add: true, delete: true, edit: true, view: true },
    sale: { add: false, delete: true, edit: true, view: true },
    purchase: { add: false, delete: true, edit: true, view: true },
    store: { add: true, delete: true, edit: true, view: true },
    user: { add: true, delete: true, edit: true, view: true },
    report: { add: true, delete: true, edit: true, view: true },
  },
  manager: {
    product: { add: true, delete: true, edit: true, view: true },
    category: { add: true, delete: true, edit: true, view: true },
    company: { add: true, delete: true, edit: true, view: true },
    sale: { add: true, delete: true, edit: true, view: true },
    purchase: { add: true, delete: true, edit: true, view: true },
    store: { add: false, delete: false, edit: true, view: true },
    user: { add: true, delete: true, edit: true, view: true },
    unit: { add: true, delete: true, edit: true, view: true },
    report: { add: true, delete: true, edit: true, view: true },
  },
  user: {
    product: { add: true, delete: false, edit: true, view: true },
    category: { add: true, delete: false, edit: true, view: true },
    company: { add: true, delete: false, edit: true, view: true },
    sale: { add: true, delete: false, edit: true, view: true },
    purchase: { add: true, delete: false, edit: true, view: true },
    store: { add: false, delete: false, edit: false, view: true },
    user: { add: false, delete: false, edit: false, view: false },
    unit: { add: true, delete: false, edit: true, view: true },
    report: { add: true, delete: true, edit: true, view: true },
  },
};
